// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTask(arg1:string,arg2:string,arg3:string):Promise<main.TaskDTO>;

export function DeleteTask(arg1:string):Promise<boolean>;

export function FilterTasks(arg1:string,arg2:string,arg3:string):Promise<Array<main.TaskDTO>>;

export function ToggleTask(arg1:string):Promise<main.TaskDTO|boolean>;
